name: 02 - Workflow Events

on: 
  #push:
  pull_request:
  #schedule:
  #  - cron: '*/10 * * * *'
  workflow_dispatch: 
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        run: echo "I have triggered by a(n) ${{ github.event_name }} event"
